### ISSUE TITLE
The component broke with the recent update

### ISSUE THREAD

**Issue by arsaboo** [finish06/unifi_access_switch#2]
Started getting with the recent controller update :(
```
2019-02-09 10:34:39 ERROR (SyncWorker_35) [custom_components.switch.unifi_access_switch] Failed to connect to Unifi: Login failed - status code: 400
```

**Comment by finish06** [comment]
The code needed updated to pyunifi 2.16.  Easy and quick update.  I think that will fix the issue.

**Comment by finish06** [comment]
Please confirm this corrected the problem.

**Comment by finish06** [comment]
Closing as confirmed via Discord issue fixed.
